# Adding missing token here
token_dict = {
    'check out': 'check_out',
    'check in': 'check_in',
    'phòng họp': 'phòng_họp',
    'thoáng mát': 'thoáng_mát',
    'món ăn': 'món_ăn',
    'mọi người' : 'mọi_người',
    'buổi sáng': 'buổi_sáng',
    'cuộc họp': 'cuộc_họp',
    'diễn ra': 'diễn_ra',
    'ra về': 'ra_về',
    'bờ sông': 'bờ_sông',
    'cuối tuần': 'cuối_tuần',
    'đồ uống': 'đồ_uống',
    'phòng chờ': 'phòng_chờ',
    'hồ bơi': 'hồ_bơi',
    'chụp hình': 'chụp_hình',
    'sống ảo': 'sống_ảo',
    'bài trí': 'bài_trí',
    'quay lại': 'quay_lại',
    'giải đấu': 'giải_đấu',
    'chữa lành': 'chữa_lành',
    'buổi tối': 'buổi_tối',
    'tươi ngon': 'tươi_ngon',
    'đúng giờ': 'đúng_giờ',
    'buổi chiều': 'buổi_chiều',
    'lá dứa': 'lá_dứa',
    'giếng trời': 'giếng_trời',
    'phương tây': 'phương_tây',
    'ghé lại': 'ghé_lại',
    'buổi tiệc': 'buổi_tiệc',
    'chuyến đi': 'chuyến_đi',
    'bãi biển': 'bãi_biển',
    'bên cạnh': 'bên_cạnh',
    'trọn vẹn': 'trọn_vẹn',
    'vẻ đẹp': 'vẻ_đẹp',
    'hợp_khẩu vị': 'hợp khẩu_vị',
    'người dùng': 'người_dùng',
    'tiếp khách': 'tiếp_khách',
    'tầm nhìn': 'tầm_nhìn',
    'hòn đảo': 'hòn_đảo',
    'cơ sở': 'cơ_sở',
    'ăn sáng': 'ăn_sáng',
    'đậm vị': 'đậm_vị',
    'ban nhạc': 'ban_nhạc',
    'hài lòng': 'hài_lòng',
    'vui cười': 'vui_cười',
    'bữa tối': 'bữa_tối',
    'tông màu': 'tông_màu',
    'màn chiếu': 'màn_chiếu',
    'đáng yêu': 'đáng_yêu',
    'mùi hương': 'mùi_hương',
    'mọi lúc mọi nơi': 'mọi_lúc_mọi_nơi',
    'nhạc_nhẹ nhàng': 'nhạc nhẹ_nhàng',
    'hoa đậu biếc': 'hoa_đậu_biếc',
    'khách mời': 'khách_mời',
    'món ăn_ở': 'món_ăn ở',
    'trần nhà': 'trần_nhà',
    'giữ vững': 'giữ_vững',
    'điểm trừ': 'điểm_trừ',
    'làm_khó khăn': 'làm khó_khăn',
    'kỳ nghỉ': 'kỳ_nghỉ',
    'đáng nhớ': 'đáng_nhớ',
    'bãi gửi xe': 'bãi_gửi_xe',
    'gọi điện': 'gọi_điện',
    'đặt phòng': 'đặt_phòng',
    'hết hạn': 'hết_hạn',
    'bữa sáng': 'bữa_sáng',
    'bảng tên': 'bảng_tên',
    'khách sạn': 'khách_sạn',
    'hồ bơi': 'hồ_bơi',
    'sân vườn': 'sân_vườn',
    'thư giãn': 'thư_giãn',
    'thành phố': 'thành_phố',
    'đông đúc': 'đông_đúc',
    'phong phú': 'phong_phú',
    'mì quảng': 'mì_quảng',
    'phòng ốc': 'phòng_ốc',
    'sạch sẽ': 'sạch_sẽ',
    'trang bị': 'trang_bị',
    'vòi xịt rửa': 'vòi_xịt_rửa',
    'nhà vệ sinh': 'nhà_vệ_sinh',
    'tuyệt vời': 'tuyệt_vời',
    'bạn_đọc sách': 'bạn đọc_sách',
    'tinh tế': 'tinh_tế',
    'béo ngậy': 'béo_ngậy',
    'khó thở': 'khó_thở',
    'giọng nói': 'giọng_nói',
    'tiệm bánh': 'tiệm_bánh',
    'bánh ngọt': 'bánh_ngọt',
    'tắm nắng': 'tắm_nắng',
    'sang chảnh': 'sang_chảnh',
    'kem dừa': 'kem_dừa',
    'đáng thử': 'đáng_thử',
    'bức tranh': 'bức_tranh',
    'phòng ngủ': 'phòng_ngủ',
    'bảng hướng_dẫn': 'bảng_hướng_dẫn',
    'phòng tập gym': 'phòng_tập_gym',
    'nét đẹp': 'nét_đẹp',
    'một sao': 'một_sao',
    'hai sao': 'hai_sao',
    'ba sao': 'ba_sao',
    'bốn sao': 'bốn_sao',
    'năm sao': 'năm_sao',
    'căn phòng': 'căn_phòng',
    'bước chân': 'bước_chân',
    'tầng trệt': 'tầng_trệt',
    'chửi tục': 'chửi_tục',
    'bức ảnh': 'bức_ảnh',
    'nước suối': 'nước_suối',
    'nước đóng_chai': 'nước_đóng_chai',
    'khó quên': 'khó_quên',
    'món ăn nhẹ': 'món_ăn_nhẹ',
    'ủi đồ': 'ủi_đồ',
    'đồ_ăn sáng': 'đồ_ăn_sáng',
    'mở_cửa sổ': 'mở cửa_sổ',
    'cảnh đẹp': 'cảnh_đẹp',
    'trong đoàn_khá_hài_lòng': 'trong_đoàn khá_hài_lòng',
    'xả stress': 'xả_stress',
    'đi chơi': 'đi_chơi',
    'thịt bò': 'thịt_bò',
    'phòng tắm': 'phòng_tắm',
    'nghe nhạc': 'nghe_nhạc',
    'thổi bóng': 'thổi_bóng',
    'bạn gái': 'bạn_gái',
    'buồng phòng': 'buồng_phòng',
    'tốt_địa điểm': 'tốt địa_điểm',
    'sữa tắm': 'sữa_tắm',
    'dầu xả': 'dầu_xả',
    'hàng ngày': 'hàng_ngày',
    'dễ mến': 'dễ_mến',
    'hoàn tiền': 'hoàn_tiền',
    'cặp đôi': 'cặp_đôi',
    'tắm biển': 'tắm_biển',
    'vấp chân': 'vấp_chân',
    'tấm gương': 'tấm_gương',
    'không gian': 'không_gian',
    'bờ cát': 'bờ_cát',
    'dọn phòng': 'dọn_phòng',
    'tắm bùn': 'tắm_bùn',
    'nhận phòng': 'nhận_phòng',
    'hiểu lầm': 'hiểu_lầm',
    'đáng có': 'đáng_có',
    'sàn nhà': 'sàn_nhà',
    'guồng quay': 'guồng_quay',
    'tan biến': 'tan_biến',
    'hít thở': 'hít_thở',
    'thiết kế': 'thiết_kế',
    'khu vực': 'khu_vực',
    'bồn tắm': 'bồn_tắm',
    'gần gũi': 'gần_gũi',
    'thiên nhiên': 'thiên_nhiên',
    'chân trần': 'chân_trần',
    'thoải mái': 'thoải_mái',
    'riêng tư': 'riêng_tư',
    'khách hàng': 'khách_hàng',
    'nhân viên': 'nhân_viên',
    'chu đáo': 'chu_đáo',
    'dọn rác': 'dọn_rác',
    'em bé_nhỏ': 'em_bé nhỏ',
    'phao bơi': 'phao_bơi',
    'thuê phòng': 'thuê_phòng',
    'đáy hồ': 'đáy_hồ',
    'biển xanh': 'biển_xanh',
    'các bạn': 'các_bạn',
    'chỗ ở': 'chỗ_ở',
    'phòng nghỉ': 'phòng_nghỉ',
    'tấm ván': 'tấm_ván',
    'ghé thăm': 'ghé_thăm',
    'ngắm biển': 'ngắm_biển',
    'hằng năm': 'hàng_năm',
    'sự_thân thiện': 'sự thân_thiện',
    'trong xanh': 'trong_xanh',
    'hạng sang': 'hạng_sang',
    'phao tắm': 'phao_tắm',
    'kính lặn': 'kính_lặn',
    'nước ép': 'nước_ép',
    'khung giờ': 'khung_giờ',
    'quầy bar': 'quầy_bar',
    'đau chân': 'đau_chân',
    'cá chẽm': 'cá_chẽm',
    'nâng cao': 'nâng_cao',
    'đèn đường': 'đèn_đường',
    'bò kho': 'bò_kho',
    'bún cá': 'bún_cá',
    'ống hút': 'ống_hút',
    'thơm dịu': 'thơm_dịu',
    'đúng nghĩa': 'đúng_nghĩa',
    'đông khách': 'đông_khách',
    'em bé': 'em_bé',
    'bức thư': 'bức_thư',
    'ngăn lại': 'ngăn_lại',
    'gọi xe': 'gọi_xe',
    'khu vui_chơi': 'khu_vui_chơi',
    'giường đôi': 'giường_đôi',
    'ố vàng': 'ố_vàng',
    'điểm cộng': 'điểm_cộng',
    'tắm bồn': 'tắm_bồn',
    'lọc khuẩn': 'lọc_khuẩn',
    'trái mít': 'trái_mít',
    'thích mắt': 'thích_mắt',
    'trẻ nhỏ': 'trẻ_nhỏ',
    'lứa tuổi': 'lứa_tuổi',
    'người già': 'người_già',
    'nét riêng': 'nét_riêng',
    'gối kê mạch': 'gối_kê_mạch',
    'gối nano': 'gối_nano',
    'gối sợi tơ': 'gối_sợi_tơ',
    'đáng tiếc': 'đáng_tiếc',
    'lối đi': 'lối_đi',
    'tuyệt đẹp': 'tuyệt_đẹp',
    'yêu thích': 'yêu_thích',
    'ở đây': 'ở_đây',
    'ở kia': 'ở_kia',
    'ở đâu': 'ở_đâu',
    'nước nóng': 'nước_nóng',
    'cả nhà': 'cả_nhà',
    'kế bên': 'kế_bên',
    'bãi cát': 'bãi_cát',
    'nụ cười': 'nụ_cười',
    'bàn ăn': 'bàn_ăn',
    'lễ tết': 'lễ_tết',
    'phun xịt': 'phun_xịt',
    'mọi thứ': 'mọi_thứ',
    'như thế_này': 'như_thế_này',
    'bãi đậu xe': 'bãi_đậu_xe',
    'góc chụp ảnh': 'góc_chụp_ảnh',
    'cát trắng': 'cát_trắng',
    'bờ biển': 'bờ_biển',
    'tăng thêm': 'tăng_thêm',
    'lúc trước': 'lúc_trước',
    'lần này': 'lần_này',
    'nơi đây': 'nơi_đây',
    'nỗi lo': 'nỗi_lo',
    'tại đây': 'tại_đây',
    'tươi mới': 'tươi_mới',
    'giữ dáng': 'giữ_dáng',
    'mang lại': 'mang_lại',
    'lần sau': 'lần_sau',
    'dạo biển': 'dạo_biển',
    'điểm đến': 'điểm_đến',
    'đây là': 'đây_là',
    'hậu_mãi tốt': 'hậu mãi_tốt',
    'phiếu chuyển tiền': 'phiếu_chuyển_tiền',
    'số điện_thoại': 'số_điện_thoại',
    'kẹt xe': 'kẹt_xe',
    'đậu xe': 'đậu_xe',
    'mỏm đá': 'mỏm_đá',
    'ga giường': 'ga_giường',
    'phát ra': 'phát_ra',
    'gió trời': 'gió_trời',
    'cây dừa': 'cây_dừa',
    'khăn tắm': 'khăn_tắm',
    'khoản tiền': 'khoản_tiền',
    'mở khoá': 'mở_khoá',
    'đổ lỗi': 'đổ_lỗi',
    'trắng mịn': 'trắng_mịn',
    'tháng tám': 'tháng_tám',
    'xanh mướt': 'xanh_mướt',
    'ẩn mình': 'ẩn_mình',
    'đá ngầm': 'đá_ngầm',
    'khu vườn': 'khu_vườn',
    'xanh mát': 'xanh_mát',
    'mến khách': 'mến_khách',
    'ngắm cảnh': 'ngắm_cảnh',
    'vây quanh': 'vây_quanh',
    'chai nhựa': 'chai_nhựa',
    'thùng xốp': 'thùng_xốp',
    'túi nilon': 'túi_nilon',
    'vững bước': 'vững_bước',
    'vươn xa': 'vươn_xa',
    'số phòng': 'số_phòng',
    'câu cá': 'câu_cá',
    'đạt chuẩn': 'đạt_chuẩn',
    'điều này': 'điều_này',
    'cúi chào': 'cúi_chào',
    'tầng hầm': 'tầng_hầm',
    'mùi hôi': 'mùi_hôi',
    'chân cẳng': 'chân_cẳng',
    'bao quanh': 'bao_quanh',
    'xước da': 'xước_da',
    'băng cá_nhân': 'băng_cá_nhân',
    'chuyện nhỏ': 'chuyện_nhỏ',
    'con người': 'con_người',
    'dễ ăn': 'dễ_ăn',
    'ngắm nhìn': 'ngắm_nhìn',
    'nhịp sống': 'nhịp_sống',
    'con sứa': 'con_sứa',
    'mùa hè': 'mùa_hè',
    'mùa xuân': 'mùa_xuân',
    'mùa thu': 'mùa_thu',
    'mùa đông': 'mùa_đông',
    'mái che': 'mái_che',
    'phòng khách': 'phòng_khách',
    'nước sốt': 'nước_sốt',
    'dao dĩa': 'dao_dĩa',
    'trơn trượt': 'trơn_trượt',
    'vách núi': 'vách_núi',
    'tảng đá': 'tảng_đá',
    'chèo thuyền': 'chèo_thuyền',
    'sân golf': 'sân_golf',
    'sân tenis': 'sân_tenis',
    'rau củ quả': 'rau_củ_quả',
    'đục đẽo': 'đục_đẽo',
    'đến đây': 'đến_đây',
    'trả phòng': 'trả_phòng',
    'gói phòng': 'gói_phòng',
    'vùng miền': 'vùng_miền'
}

# Adding lemmatization dictionary for reducing meaning interference
lemmatization_dict = {
    'check_out': 'checkout',
    'check_in': 'checkin',
    'mình': 'tôi',
    'ngộ': 'tôi',
    'tao': 'tôi',
    'tau': 'tôi',
    'mày': 'bạn',
    'ní': 'bạn',
    'oke': 'ok',
    'okay': 'ok',
    'oki': 'ok',
    'nhiêt tình': 'nhiệt tình',
    'cám ơn': 'cảm ơn',
    'mng': 'mọi người',
    'phuc vụ': 'phục vụ',
    'bày trí': 'bài trí',
    'mọt thứ': 'mọi thứ',
    'khách san': 'khách sạn',
    'phục vục': 'phục vụ',
    'ứng tượng': 'ấn tượng',
    'thức uống': 'đồ uống',
    'nước uống': 'đồ uống',
    'phu hợp': 'phù hợp',
    'dù lịch': 'du lịch',
    'du lich': 'du lịch',
    'giá đình': 'gia đình',
    'độc sách': 'đọc sách',
    'band nhạc': 'ban nhạc',
    'thân thiệt': 'thân thiện',
    'vẻ hình': 'vẽ hình',
    'thanh viên': 'thành viên',
    'thương thức': 'thưởng thức',
    'trải nhiệm': 'trải nghiệm',
    'khác hàng': 'khách hàng',
    'phụ vụ': 'phục vụ',
    'quá trinh': 'quá trình',
    'giải tri': 'giải trí',
    'dịch vu': 'dịch vụ',
    'tronh': 'trong',
    'đắt địa': 'đắc địa',
    'tính tế': 'tinh tế',
    'kì nghỉ': 'kỳ nghỉ',
    'phòng gym': 'phòng tập gym',
    'nhận viên': 'nhân viên',
    'nghĩ ngơi': 'nghỉ ngơi',
    'xả stres': 'xả stress',
    'nắm ngoái': 'năm ngoái',
    'mòn ăn': 'món ăn',
    'trải ngiệm': 'trải nghiệm',
    'nhận viên': 'nhân viên',
    'gía trị': 'giá trị',
    'nhưn': 'nhưng',
    'nhg': 'nhưng',
    'đc': 'được',
    'trc': 'trước',
    'mng': 'mọi người',
    'đi chuyển': 'di chuyển',
    'nhẹn nhàng': 'nhẹ nhàng',
    'vầ': 'và',
    'viêw': 'view',
    'xung quoanh': 'xung quanh',
    'nhà hằng': 'nhà hàng',
    'tận hường': 'tận hưởng',
    'gd': 'gia đình',
    'gđ': 'gia đình',
    'tạn tình': 'tận tình',
    'thiên thiện': 'thân thiện',
    'thân thiệt': 'thân thiện',
    'cảnh quang': 'quang cảnh',
    'quan cảnh': 'quang cảnh',
    'karaok' : 'karaoke',
    'đây đủ' : 'đầy đủ',
    'sịn so': 'xịn xò',
    'check - in': 'check in',
    'thoái mái': 'thoải mái',
    'du lich': 'du lịch',
    'ngỉ dưỡng': 'nghỉ dưỡng',
    'nghĩ hè': 'nghỉ hè',
    'hồi bơi': 'hồ bơi',
    'thân thiên': 'thân thiện',
    'giơi thiệu': 'giới thiệu',
    'nghĩ ngơi': 'nghỉ ngơi',
    'ngặt hái': 'gặt hái',
    'phòng phú': 'phong phú',
    'sáng trọng': 'sang trọng',
    'dể chịu': 'dễ chịu',
    'tata show': 'tatashow ',
    '0': 'không',
    '1': 'một',
    '2': 'hai',
    '3': 'ba',
    '4': 'bốn',
    '5': 'năm',
    '6': 'sáu',
    '7': 'bảy',
    '8': 'tám',
    '9': 'chín',
    '10': 'mười',
    'đồ ăn': 'món ăn',
    'iu': 'yêu',
}
